#!/usr/bin/env sh
set -eu

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" <<-EOSQL
  CREATE USER ${POSTGRES_APP_USER} WITH PASSWORD '${POSTGRES_APP_PASSWORD}';
  CREATE DATABASE ${POSTGRES_APP_DB} OWNER ${POSTGRES_APP_USER};
  CREATE DATABASE ${POSTGRES_TEST_DB} OWNER ${POSTGRES_APP_USER};
  GRANT ALL PRIVILEGES ON DATABASE ${POSTGRES_APP_DB} TO ${POSTGRES_APP_USER};
  GRANT ALL PRIVILEGES ON DATABASE ${POSTGRES_TEST_DB} TO ${POSTGRES_APP_USER};
EOSQL

