name: CI

on:
  push:
    branches: ["master"]
  pull_request:

jobs:
  python:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: astral-sh/setup-uv@v5
      - name: Install dependencies
        run: uv sync
      - name: Lint
        run: make lint
      - name: Test
        run: make test

